### ISSUE TITLE
What is the correct package name for this library?

### ISSUE THREAD

**Issue by yurishkuro** [xdg-go/scram#3]
The README recommends `import "github.com/xdg/scram"`, but the actual path is `github.com/xdg-go/scram`. Since there's no sub-packages and no `go.mod` file it might work with both, but it would be best to converge onto the actual repo name `xdg-go`.

**Comment by xdg** [comment]
It was renamed in 2018, but thanks to Github redirects, consumers never noticed until I recently added a go.mod file.  I've recreated `xdg/scram` prior to it gaining go.mod for backwards compat.  The correct name going forward as a module is 'xdg-go/scram'.
