### ISSUE TITLE
github.com/xdg/stringprep  path changed

### ISSUE THREAD

**Issue by azhaochen** [xdg-go/scram#4]
github.com/xdg/stringprep  jump to  github.com/xdg-go/stringprep，and its import path required “xdg-go”

**Comment by xdg** [comment]
It was renamed in 2018, but thanks to Github redirects, consumers never noticed until I added a go.mod file.  I've recreated `xdg/scram` prior to it gaining go.mod.

**Comment by xdg** [comment]
I've also done a retrospective on what happened: https://xdg.me/i-broke-the-mongodb-go-driver-ecosystem/
