### ISSUE TITLE
module declares its path as github.com/xdg-go/scram but was required as: github.com/xdg/scram

### ISSUE THREAD

**Issue by srPuebla** [xdg-go/scram#5]
Hi,

URL seems to be changed. How can i solve in my projects?

go get: github.com/xdg/scram@v0.0.0-20180814205039-7eeb5667e42c updating to
        github.com/xdg/scram@v1.0.2: parsing go.mod:
        module declares its path as: github.com/xdg-go/scram
                but was required as: github.com/xdg/scram

Thanks

**Comment by rubengp99** [comment]
I've the same issue.

**Comment by dudleycodes** [comment]
I've had this pop up in my build upgrades as well

![2021-03-30 12 26 43](https://user-images.githubusercontent.com/12804982/113030448-386e5500-9153-11eb-9d1c-f4d7444e3eed.png)

**Comment by xdg** [comment]
It was renamed in 2018, but thanks to Github redirects, consumers never noticed until I added a go.mod file.  I've recreated `xdg/scram` prior to it gaining go.mod.

**Comment by dudleycodes** [comment]
For anyone Googling, looks like my issue was triggered by mongo-go-driver; and looks like it'll be addressed in the 1.15.1 release.

https://github.com/mongodb/mongo-go-driver/pull/624

**Comment by xdg** [comment]
I've also done a retrospective on what happened: https://xdg.me/i-broke-the-mongodb-go-driver-ecosystem/
