### ISSUE TITLE
Module name change breaking

### ISSUE THREAD

**Issue by rubengp99** [xdg-go/scram#6]
Is there any fix for this?
```
go get -u ./...
go get: github.com/xdg/scram@v0.0.0-20180814205039-7eeb5667e42c updating to
	github.com/xdg/scram@v1.0.2: parsing go.mod:
	module declares its path as: github.com/xdg-go/scram
	        but was required as: github.com/xdg/scram
```

I'm not using this package directly. It seems to be pulled with the MongoDB dependencies.

**Comment by xdg** [comment]
I've recreated `xdg/scram` before it became a module.

**Comment by lawmatsuyama** [comment]
Hi! Could you please generate a tag for xdg/scram?

**Comment by xdg** [comment]
@lawmatsuyama sure.  v0.0.1 now tagged.

**Comment by xdg** [comment]
I've also done a retrospective on what happened: https://xdg.me/i-broke-the-mongodb-go-driver-ecosystem/
