### ISSUE TITLE
Can you add topics in this repository?

### ISSUE THREAD

**Issue by Neustradamus** [xdg-go/scram#7]
Dear @xdg-go,

I wish you a Happy New Year!

Can you add in this repository, topics?
- scram
- scram-sha-1
- scram-sha-256

Thanks in advance.

**Comment by xdg** [comment]
I don't understand what you mean by "topics". Can you elaborate?

**Comment by Neustradamus** [comment]
@xdg: Yes, of course!

Here: https://github.com/xdg-go/scram/ at right, click on the gear in "About" section ^^

You can add other topics too.

Example of a complete lib with all possibilities: https://github.com/topics/scram-sha-224

About repository description: You can update to:
`Go implementation of RFC5802 "Salted Challenge Response Authentication Mechanism (SCRAM) SASL and GSS-API Mechanisms" and RFC7677 "SCRAM-SHA-256 and SCRAM-SHA-256-PLUS Simple Authentication and Security Layer (SASL) Mechanisms"`

About README, you can update:
"scram – Go implementation of RFC-5802" to "scram – Go implementation of RFC5802 and RFC7677"

Thanks in advance.

**Comment by xdg** [comment]
I've added "scram", but the others are too specific IMO.

**Comment by Neustradamus** [comment]
@xdg: Do you want that people do not found your lib?
- https://github.com/topics/scram-sha-1
- https://github.com/topics/scram-sha-256

**Comment by Neustradamus** [comment]
@xdg: Please note that some projects which use your lib have SCRAM-SHA-512 support too.

**Comment by xdg** [comment]
I think Google and pkg.go.dev are sufficient for people to find it.
